In [51]:
import numpy as np
import random
from sklearn import preprocessing

In [52]:
N = 13
input_data = np.random.uniform(-9.9, 9.9 ,(N,N))
print(input_data)   

[[ 8.4640632  -4.35912831  5.76255089 -9.0718134   6.64124905  5.56715082
  -5.27620046 -3.23082405 -3.27482855  8.24355687 -5.04515965  7.47508835
  -2.23172181]
 [-7.05475327 -3.11780456 -5.53352104  0.10633691 -9.23302922 -7.82469705
   8.42276594  9.24681998  2.66419509 -0.4550888   2.79614949  2.06666624
  -8.5216124 ]
 [ 6.6718497  -0.84699894  4.42911931 -2.7446929  -9.65769832  7.79706726
  -2.7278592  -7.32391597  7.3688421  -4.42309809  1.77905281  9.27347531
   7.28090828]
 [ 7.96397125 -2.46314119 -1.07168146 -9.82704493 -6.81532031 -1.08708473
  -2.07659925 -5.64653373 -8.76262436 -7.76083282  5.46709146 -5.21389762
   7.32265614]
 [ 0.32804714  5.2158206  -9.674817   -0.1157773   4.29788627 -5.01140718
  -3.28466107  8.96557946 -1.61167283  2.64374534 -0.12561632 -5.09569742
   8.17951643]
 [ 5.55616982  4.46772589 -6.7763055   3.79614414 -4.59445244 -5.3599656
  -6.52162878  6.91025961  8.30930853  2.55831909  1.80362514 -1.86723509
  -5.43479374]
 [-6.85548758  5.403010

In [53]:
# Бинаризация данных
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\nBinarized data:\n", data_binarized)



Binarized data:
 [[1. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1.]
 [1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1.]
 [1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0.]]


In [54]:
# Вывод среднего значения и стандартного отклонения
print("\nBEFORE:")
print("Mean =", input_data.mean(axis=0))
print("Std deviaton =", input_data.std(axis=0))


BEFORE:
Mean = [ 2.52833623  2.20484432 -0.97877617 -2.94190652 -0.37357041 -1.98969048
 -2.25858928 -0.04042814 -0.26380771  2.11181877  1.4683702   0.93468161
 -0.89643364]
Std deviaton = [6.07683072 4.44177815 7.06850314 4.57869573 7.04761738 5.60564884
 5.00711547 6.60191637 5.76108088 4.74641595 3.4706659  5.18906869
 6.68189593]


In [55]:
# Исключение среднего
data_scaled = preprocessing.scale(input_data)
print("\nAFTER:")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))


AFTER:
Mean = [-1.49453099e-16 -1.36642834e-16 -5.12410627e-17  1.02482125e-16
  3.41607085e-17  1.28102657e-16  8.54017711e-17  1.70803542e-17
 -1.70803542e-17 -1.28102657e-17 -8.54017711e-18 -2.56205313e-17
  3.41607085e-17]
Std deviation = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [56]:
# Масштабирование MinMax
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\n Min max scaled data:\n", data_scaled_minmax)


 Min max scaled data:
 [[0.91760787 0.         0.80029694 0.05079141 0.89630071 0.8715773
  0.24377988 0.27759404 0.36175785 0.95587347 0.         0.8779025
  0.42031598]
 [0.         0.0982566  0.21469116 0.6680474  0.02656424 0.10032987
  1.         0.96534583 0.6889756  0.43634072 0.60565945 0.51070968
  0.07010317]
 [0.81163656 0.27800153 0.73116979 0.47630776 0.00329702 1.
  0.38445523 0.05198805 0.94818386 0.19934856 0.52709933 1.
  0.94996668]
 [0.88803807 0.15007628 0.4459998  0.         0.15902819 0.48835445
  0.42040655 0.14444321 0.05940105 0.         0.81196189 0.01641193
  0.95229115]
 [0.43653559 0.75790217 0.         0.65310961 0.76791011 0.26234952
  0.35371826 0.94984421 0.45339144 0.62142077 0.37998348 0.02443687
  1.        ]
 [0.74566783 0.69868696 0.1502633  0.91619715 0.28070741 0.24227576
  0.17502885 0.83655761 1.         0.61631863 0.52899728 0.24362617
  0.24197316]
 [0.01178233 0.77271915 0.00602252 0.44501169 0.48238897 0.63785574
  0.24346144 0.70037584 0.

In [58]:
input_data[0, 0] = input_data[0, 0]*50000

In [59]:
# Нормализация данных
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nL1 normalized data:\n", data_normalized_l1)
print("\nL2 normzlized data:\n", data_normalized_l2)


L1 normalized data:
 [[ 0.11339342 -0.05839943  0.07720114 -0.12153548  0.0889731   0.07458336
  -0.07068549 -0.04328349 -0.04387302  0.11043929 -0.06759022  0.10014408
  -0.02989847]
 [-0.1052266  -0.04650425 -0.08253635  0.00158609 -0.13771712 -0.11671085
   0.12563147  0.13792282  0.03973834 -0.00678797  0.04170653  0.03082578
  -0.12710583]
 [ 0.09224872 -0.01171108  0.06123948 -0.03794966 -0.13353273  0.10780661
  -0.0377169  -0.10126455  0.10188573 -0.06115622  0.02459818  0.12822025
   0.1006699 ]
 [ 0.11141775 -0.0344599  -0.01499306 -0.13748257 -0.09534786 -0.01520856
  -0.02905209 -0.07899628 -0.12259109 -0.1085758   0.07648584 -0.0729436
   0.10244561]
 [ 0.00601367  0.09561498 -0.17735607 -0.0021224   0.07878766 -0.09186773
  -0.0602135   0.16435452 -0.02954474  0.04846441 -0.00230276 -0.09341292
   0.14994463]
 [ 0.08687497  0.06985632 -0.10595273  0.05935562 -0.07183778 -0.08380717
  -0.10197066  0.1080472   0.1299224   0.04000128  0.02820106 -0.02919565
  -0.08497716]
 