In [26]:
import numpy as np
import random
from sklearn import preprocessing

In [27]:
N = 13
input_data = np.random.uniform(-9.9, 9.9 ,(N,N))
print(input_data)   

[[-1.30236244  7.1493437  -8.23874583  9.10134784 -0.8579457  -3.94479861
   9.39975844  7.20338566  1.65782054 -7.80086483  4.51931187  5.14825075
  -7.635482  ]
 [-2.20483171 -8.76456817 -2.24193121  1.55714229  2.00533726 -9.10033975
  -6.51164778 -9.74866801  4.31294047  2.19057202  3.22726    -0.90484413
  -3.22146138]
 [ 8.50528374  2.69181382 -6.54225489  2.04425802 -4.00159978  7.78218357
  -3.81338455  9.62183224 -6.40143781 -3.95560403 -9.12128074  8.84366638
  -3.55170698]
 [ 3.92306686 -7.06742519 -4.02255752  2.61981677 -6.63928471  4.66125156
  -5.69932381 -0.93570594 -2.05969494  6.60390373 -5.17992193 -5.45013397
  -9.67115577]
 [ 7.74347365 -5.41582535 -5.13810401 -6.12083527 -4.29857625  3.00529084
   4.66358897  1.91643135  6.40720685 -2.65579032  2.04283771  6.53095238
  -3.21190937]
 [-5.77057758 -6.35756152 -1.46168511 -2.7228471   5.10552366  3.78880662
   3.63046851 -1.96217356  8.61855246  7.18432487  7.90888156  4.48050586
  -1.59986238]
 [-6.4019721   9.48461

In [28]:
# Бинаризация данных
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\nBinarized data:\n", data_binarized)



Binarized data:
 [[0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1.]
 [0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]]


In [29]:
# Вывод среднего значения и стандартного отклонения
print("\nBEFORE:")
print("Mean =", input_data.mean(axis=0))
print("Std deviaton =", input_data.std(axis=0))


BEFORE:
Mean = [ 0.2801555  -2.66320851 -2.98660118  2.11672184  0.0390803  -0.52987193
  0.97447245  1.6662675   1.65148461 -0.50688278  1.29290538  1.30776755
 -1.93072998]
Std deviaton = [5.33124663 5.95490445 4.29518022 4.57957703 5.72791448 6.02478484
 5.84945047 6.06387649 5.54739251 5.90985706 4.27341921 5.07231578
 5.72084926]


In [30]:
# Исключение среднего
data_scaled = preprocessing.scale(input_data)
print("\nAFTER:")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))


AFTER:
Mean = [-4.27008856e-17 -8.96718597e-17 -1.70803542e-17 -3.41607085e-17
  5.12410627e-17  0.00000000e+00 -1.81478764e-17 -3.41607085e-17
  7.68615940e-17  5.12410627e-17 -8.54017711e-18 -1.70803542e-17
  1.32372745e-16]
Std deviation = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [31]:
# Масштабирование MinMax
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\n Min max scaled data:\n", data_scaled_minmax)


 Min max scaled data:
 [[0.34208909 0.8773638  0.07459612 1.         0.4116759  0.29064579
  0.99066314 0.86703711 0.54924904 0.06684913 0.80096668 0.76146102
  0.11073017]
 [0.28155017 0.04164941 0.43803029 0.51144364 0.57251171 0.
  0.03234514 0.         0.71840617 0.65823246 0.72509824 0.3707339
  0.35083017]
 [1.         0.64327793 0.17741117 0.54298884 0.23509114 0.95175934
  0.19485713 0.99073203 0.03579538 0.29444634 0.         1.
  0.33286651]
 [0.69261835 0.13077437 0.33011626 0.58026154 0.08692758 0.77581548
  0.08127009 0.45075159 0.31240691 0.91945323 0.23143401 0.07733556
  0.        ]
 [0.94889669 0.21750765 0.26250908 0.01422431 0.21840943 0.68246
  0.70541139 0.59662824 0.85183145 0.37138103 0.65554974 0.85071437
  0.35134975]
 [0.04235485 0.16805265 0.48531675 0.23427515 0.74665482 0.72663103
  0.64318823 0.39825143 0.99271581 0.95380778 1.         0.7183581
  0.4390368 ]
 [0.         1.         1.         0.87942964 1.         0.60010656
  0.74267981 0.09362423 1.   

In [32]:
# Нормализация данных
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\n L1 normalized data:\n", data_normalized_l1)
print("\nL2 normzlized data:\n", data_normalized_l2)


 L1 normalized data:
 [[-0.01760915  0.09666576 -0.11139549  0.12305867 -0.01160022 -0.05333734
   0.12709346  0.09739646  0.02241527 -0.10547493  0.06110529  0.06960913
  -0.10323881]
 [-0.03937794 -0.15653378 -0.04004053  0.02781031  0.035815   -0.16253061
  -0.11629699 -0.17410965  0.07702843  0.03912327  0.05763835 -0.01616037
  -0.05753478]
 [ 0.11063596  0.03501487 -0.08510106  0.02659152 -0.05205245  0.10122994
  -0.04960416  0.12515992 -0.08326932 -0.05145414 -0.11864879  0.11503761
  -0.04620028]
 [ 0.06079141 -0.10951604 -0.06233311  0.04059639 -0.10288162  0.07223024
  -0.08831609 -0.0144996  -0.03191681  0.10233336 -0.0802675  -0.08445467
  -0.14986316]
 [ 0.13091067 -0.0915596  -0.08686446 -0.10347845 -0.07267145  0.05080725
   0.07884234  0.03239907  0.10831983 -0.04489862  0.03453608  0.11041186
  -0.05430033]
 [-0.09523699 -0.1049245  -0.02412349 -0.04493757  0.08426101  0.06253005
   0.05991686 -0.0323835   0.14223965  0.11856932  0.13052732  0.07394578
  -0.02640395]